name: tests
on: 
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python verion ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install mptcplib package in dev mode and pytest
        run: |
          make dev-install
          pip install pytest
      - name: Printing the linux kernel version for debug
        run: |
          uname -r 
      - name: Test with pytest
        run: |
          pytest mptcplib/test/