name: tests

on: 
  push:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package in dev mode and pytest
        run: |
          sudo sysctl -w net.mptcp.enabled=1
          uname -r
          make dev-install
          pip install pytest
    
      - name: Test with pytest
        run: |
          pytest mptcplib/test/